import { createClient } from '@supabase/supabase-js';
import fs from 'fs/promises';
import path from 'path';

export async function generateTypes() {
  // This should be run from the project root
  const types = `// This file is auto-generated by scripts/generate-types.ts
// Do not edit this file directly

export type WaitlistEntry = {
  id: string;
  email: string;
  created_at: string;
  updated_at?: string;
  metadata?: Record<string, any>;
};

// Add other database types as needed
`;

  const outputPath = path.join(process.cwd(), 'src/types/database.types.ts');
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, types, 'utf-8');
  console.log(`✅ Generated types at ${outputPath}`);
}

generateTypes().catch(console.error);
